name: 'Build Container'
description: 'Builds a container'
inputs:
  TAG:
    description: 'Tag of the container image'
    required: true
  IMAGE_NAME:
    description: 'Name of the container image'
    required: true
runs:
  using: "composite"
  steps:
    - name: Build Container
      shell: bash
      run: docker build --tag "${IMAGE_TAG}" -f Containerfile . && docker save --output "${{ inputs.IMAGE_NAME }}.tar" "${IMAGE_TAG}"
      env:
        IMAGE_TAG: "${{ inputs.IMAGE_NAME }}:${{ inputs.TAG }}"
    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.IMAGE_NAME }}
        path: ${{ inputs.IMAGE_NAME}}.tar
        retention-days: 1
